server:
  port: 7476

spring:
  application:
    name: neo4j
  datasource:
    driver-class-name: org.neo4j.jdbc.bolt.BoltDriver
    name: neo4j
    password: 123456
    url: jdbc:neo4j:bolt://localhost:7687

  data:
    neo4j:
#      uri: http://127.0.0.1:7474
      uri: file:////d:/tmp/graph
      username: neo4j
      password: 123456
      embedded:
        enabled: true
