server:
  port: 8080

spring:
  application:
    name: cloud-admin
  freemarker:
    enabled: true
    charset: UTF-8
    suffix: .ftl
    check-template-location: true
    template-loader-path: ["classpath:/templates/"]
    request-context-attribute: ctx
    content-type: text/html;charset=UTF-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    settings:
      locale: zh_CN
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      template_update_delay: 10
      number_format: #.##
  resources:
    static-locations: ["classpath:/META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/public/","classpath:/templates/"]
  data:
    mongodb:
      uri: mongodb://localhost:27017/cloud-admin
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554462
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 100ms
      key-deserializer: org.apache.kafka.common.serialization.ShortDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ShortDeserializer
logging:
  level:
    root: info
    io.micrometer: warn

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      influx:
        enabled: true
        db: spring
        uri: http://localhost:8086
        step: 10s
        user-name: admin
        password: admin

