DROP TABLE IF EXISTS user;

CREATE TABLE user
(
  id BIGINT(20) NOT NULL COMMENT '主键ID',
  username VARCHAR(50) NOT NULL COMMENT '用户名',
  email VARCHAR(100) DEFAULT NULL COMMENT '邮箱',
  mobile CHAR(11) DEFAULT  NULL COMMENT '手机号',
  create_time TIMESTAMP COMMENT '创建时间',
  update_time TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id)
);
