spring:
  application:
    name: search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
  elasticsearch:
    rest:
      uris: ["http://127.0.0.1:9200"]
